# Generated by Django 5.2.8 on 2025-12-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование поставщика')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AlterUniqueTogether(
            name='booksection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='booksection',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booksection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sections',
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name': 'Автор книги', 'verbose_name_plural': 'Авторы книг'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='patronymic',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publication_year',
            new_name='publish_year',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе (шт)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.publisher', verbose_name='Издательство'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название раздела'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена закупки')),
                ('supply_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Книга')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поступление',
                'verbose_name_plural': 'Поступления',
            },
        ),
        migrations.DeleteModel(
            name='BookGenre',
        ),
        migrations.DeleteModel(
            name='BookSection',
        ),
    ]
